  - name: Disable SELinux
    selinux:
      state: disabled
    when: ansible_os_family == "RedHat"

  - name: istall Apache
    yum:
      name: httpd
      state: latest


  - name: start and enable Apache
    systemd:
      state: started
      enabled: yes
      name: httpd

  - name: Download template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page285/farmfresh.zip
      dest: /tmp/farmfresh.zip

  - name: Install Unzip
    yum:
      name: unzip
      state: latest

  - name: Unarchive
    unarchive:
      src: /tmp/farmfresh.zip
      dest: /tmp/
      remote_src: yes

  - name: Move files to html
    shell: "mv /tmp/organic-farm-website-template/* /var/www/html/"
    args:
      creates: /var/www/html/contact.html

  - name: Permissionss
    file:
      path: /var/www/html
      owner: apache
      group: apache
      recurse: yes




- hosts: all
  tasks:
  - debug:
      msg: "Variable is {{ ansible_os_family }}"

  - name: Install Apache on CentOS
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Download template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page285/farmfresh.zip
      dest: /tmp/farmfresh.zip
    
